/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.Patient;

import Model.Community.CommunityDirectory;
import UI.Encounter.NewPatientEncounterJPanel;
import Model.Doctor.DoctorDirectory;
import Model.Encounter.EncounterDirectory;
import Model.Hospital.HospitalDirectory;
import Model.Patient.PatientDirectory;
import Model.SignUp.SignUpDirectory;
import Model.Vitals.VitalsDirectory;
import UI.Encounter.EncounterRecordsJPanel;

/**
 *
 * @author UshaSingh
 */
public class IndividualPatientLoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form IndividualPatientLoginJFrame
     */
    SignUpDirectory SignUpDirectory;
    HospitalDirectory HospitalDirectory;
    DoctorDirectory DoctorDirectory;
    PatientDirectory PatientDirectory;
    EncounterDirectory EncounterDirectory;
    VitalsDirectory VitalsDirectory;
    CommunityDirectory CommunityDirectory;
    String PtID;
    public IndividualPatientLoginJFrame(SignUpDirectory SignUpDirectory,HospitalDirectory HospitalDirectory,DoctorDirectory DoctorDirectory,String PtID, PatientDirectory PatientDirectory, EncounterDirectory EncounterDirectory, VitalsDirectory VitalsDirectory, CommunityDirectory CommunityDirectory) {
        initComponents();
        this.SignUpDirectory = SignUpDirectory;
        this.HospitalDirectory = HospitalDirectory;
        this.DoctorDirectory = DoctorDirectory;
        this.PatientDirectory = PatientDirectory;
        this.EncounterDirectory = EncounterDirectory;
        this.VitalsDirectory = VitalsDirectory;
        this.PtID = PtID;
        this.CommunityDirectory = CommunityDirectory;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitIndividualPatientPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnRaiseEncounter = new javax.swing.JButton();
        btnEncounterRecords = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnVitalsHistory = new javax.swing.JButton();
        btnHospitalSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnRaiseEncounter.setBackground(new java.awt.Color(0, 153, 153));
        btnRaiseEncounter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRaiseEncounter.setText("Raise Encounter");
        btnRaiseEncounter.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRaiseEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRaiseEncounterActionPerformed(evt);
            }
        });

        btnEncounterRecords.setBackground(new java.awt.Color(0, 153, 153));
        btnEncounterRecords.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEncounterRecords.setText("<html>\n<center>\nEncounter <br> Records\n</center>\n</html>");
        btnEncounterRecords.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnEncounterRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterRecordsActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(0, 153, 153));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnVitalsHistory.setBackground(new java.awt.Color(0, 153, 153));
        btnVitalsHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnVitalsHistory.setText("Vitals History");
        btnVitalsHistory.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVitalsHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitalsHistoryActionPerformed(evt);
            }
        });

        btnHospitalSearch.setBackground(new java.awt.Color(0, 153, 153));
        btnHospitalSearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHospitalSearch.setText("Hospital Search");
        btnHospitalSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHospitalSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHospitalSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRaiseEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                    .addComponent(btnEncounterRecords)
                    .addComponent(btnVitalsHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnHospitalSearch)
                .addGap(32, 32, 32)
                .addComponent(btnRaiseEncounter)
                .addGap(40, 40, 40)
                .addComponent(btnEncounterRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnVitalsHistory)
                .addGap(117, 117, 117)
                .addComponent(btnLogOut)
                .addContainerGap(327, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEncounterRecords, btnHospitalSearch, btnLogOut, btnRaiseEncounter, btnVitalsHistory});

        splitIndividualPatientPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );

        splitIndividualPatientPane.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitIndividualPatientPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitIndividualPatientPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRaiseEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRaiseEncounterActionPerformed
        // TODO add your handling code here:
        NewPatientEncounterJPanel loginuserpanel = new NewPatientEncounterJPanel(SignUpDirectory, HospitalDirectory, DoctorDirectory, PtID, PatientDirectory, EncounterDirectory);
        splitIndividualPatientPane.setRightComponent(loginuserpanel);
        
    }//GEN-LAST:event_btnRaiseEncounterActionPerformed

    private void btnEncounterRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterRecordsActionPerformed
        // TODO add your handling code here:
        EncounterRecordsJPanel loginuserpanel = new EncounterRecordsJPanel(SignUpDirectory, HospitalDirectory, DoctorDirectory,PatientDirectory,PtID, EncounterDirectory);
        splitIndividualPatientPane.setRightComponent(loginuserpanel);
    }//GEN-LAST:event_btnEncounterRecordsActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new PatientLoginJFrame (SignUpDirectory, HospitalDirectory, DoctorDirectory, PatientDirectory, EncounterDirectory, VitalsDirectory, CommunityDirectory).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnHospitalSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalSearchActionPerformed
        // TODO add your handling code here:
        HospitalSearchJPanel loginuserpanel = new HospitalSearchJPanel(SignUpDirectory, HospitalDirectory, DoctorDirectory,PatientDirectory,EncounterDirectory, VitalsDirectory, CommunityDirectory);
        splitIndividualPatientPane.setRightComponent(loginuserpanel);
    }//GEN-LAST:event_btnHospitalSearchActionPerformed

    private void btnVitalsHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitalsHistoryActionPerformed
        // TODO add your handling code here:
        VitalsSearchJPanel loginuserpanel = new VitalsSearchJPanel(SignUpDirectory, HospitalDirectory, DoctorDirectory,PatientDirectory,EncounterDirectory, VitalsDirectory, CommunityDirectory, PtID);
        splitIndividualPatientPane.setRightComponent(loginuserpanel);
    }//GEN-LAST:event_btnVitalsHistoryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualPatientLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualPatientLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualPatientLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualPatientLoginJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new IndividualPatientLoginJFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncounterRecords;
    private javax.swing.JButton btnHospitalSearch;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRaiseEncounter;
    private javax.swing.JButton btnVitalsHistory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane splitIndividualPatientPane;
    // End of variables declaration//GEN-END:variables
}
